### ISSUE TITLE
test

### ISSUE THREAD

**Issue by cranium7811** [DeGatchi/basic-treasury-rewarder#2]
https://github.com/DeGatchi/basic-treasury-rewarder/blob/0b0b886bc075b301d24417ffea75249b65d1373b/src/test/Contract.t.sol#L71-L88

just letting you know, nothing big though. `testClaimRewards()` is failing since `hevm.stopPrank()` is not there in `testReleaseRewards()` and similarly `testFailDepositEthAfterClaim()` fails because of that and not because of depositing eth after claim.

<img width="591" alt="Screenshot 2022-09-20 at 6 43 41 PM" src="https://user-images.githubusercontent.com/54663490/191268010-c65a0e60-7129-4d7f-bd05-5cb494944d1d.png">

**Comment by degatchi** [comment]
we must be using different versions of foundry bc mine passed! 
![image](https://user-images.githubusercontent.com/72078332/191271119-2fae3767-a78e-4ae2-9c34-684886e2f028.png)
